# Exclude component "addToPath" for TGZ & ZIP.
if (CPACK_GENERATOR MATCHES "^(TGZ|ZIP|DEB|RPM)$")
  list(REMOVE_ITEM CPACK_COMPONENTS_ALL "addToPath")
endif()

# Need to set 'CMAKE_<GENERATOR>_COMPONENT_INSTALL' to ON, otherwise CPack ignores CPACK_COMPONENTS_ALL variable
set(CPACK_ARCHIVE_COMPONENT_INSTALL ON)
set(CPACK_RPM_COMPONENT_INSTALL ON)
set(CPACK_DEB_COMPONENT_INSTALL ON)
